### ISSUE TITLE
Can't connect to spdyd

### ISSUE THREAD

**Issue by igrigorik** [romanbsd/spdy#1]
```
bin/spdyd -v -s -p 8000
Starting server on port: 8000 SSL: ON
I, [21:02:23.991609] Connection from: xxx.xxx.xx.xx
I, [21:02:23.991870] Connection from: xxx.xxx.xx.xx
I, [21:02:24.069932] Disconnected: xxx.xxx.xx.xx
I, [21:02:24.070255] Disconnected: xxx.xxx.xx.xx
I, [21:02:24.141925] Connection from: xxx.xxx.xx.xx
D, [21:02:24.218181] receive_data 444 bytes
WARNING net/spdy/spdy_framer.cc(614) Unexpectedly large frame.  Spdy session is likely corrupt.
WARNING net/spdy/spdy_framer.cc(763) inflate failure: -3
ERROR module.cc(55) SpdyFramer error: DECOMPRESS_FAILURE
```

Running Chrome 17.0.953.0 canary. Have you ran into this?

**Comment by romanbsd** [comment]
Nope. Is it possible that the Chrome sends something other than SPDY frames at this point? Other than that, the frame format may have changed, but I don't think so.

**Comment by igrigorik** [comment]
Good question, any debug flags I can enable (short of instrumenting the code?) I do have NPN enabled, so I would have expected it to switch to SPDY automatically.

**Comment by epitron** [comment]
I'm getting a similar problem with Chrome v16:

```
$ rackup -s Spdy config.ru
Loading...
Starting server on port: 9292 SSL: OFF
I, [17:34:48.875817] Connection from: 127.0.0.1
I, [17:34:48.875984] Connection from: 127.0.0.1
WARNING net/spdy/spdy_framer.cc(614) Unexpectedly large frame.  Spdy session is likely corrupt.
WARNING net/spdy/spdy_framer.cc(763) inflate failure: -3
ERROR module.cc(55) SpdyFramer error: DECOMPRESS_FAILURE
I, [17:35:05.903140] Disconnected: 127.0.0.1
```

**Comment by romanbsd** [comment]
To tell the truth, I never tried it with the recent chromium, because of the awkward NPN thingy. I was once hoping that NPN would be possible over HTTP/1.1, as a simple matter of headers. Alas, it didn't happen.
Sadly I don't have any time to invest in this. My guess is that that Chrome(ium) is sending some SSL w/NPN packets which are not being handled. If you can provide some tcpdump/wireshark dump, it might be helpful.

**Comment by tillsc** [comment]
A little Workaround: Starting a recent Chrome version with option --use-spdy=no-ssl did work for us

**Comment by tibbon** [comment]
I'm having this issue as well. I've tried  Chrome 19.0.1084.36 beta and also Chrome 20.0.1124.0 canary. If its requiring browser tweaks, it definitely isn't something I can use for production (yet). Also Firefox 5 and 12. 

`Starting server on port: 9292 SSL: OFF
I, [10:39:47.156911] Disconnected: 127.0.0.1
I, [10:39:47.165218] Connection from: 127.0.0.1
WARNING net/spdy/spdy_framer.cc(614) Unexpectedly large frame.  Spdy session is likely corrupt.
WARNING net/spdy/spdy_framer.cc(763) inflate failure: -3
ERROR module.cc(55) SpdyFramer error: DECOMPRESS_FAILURE`

**Comment by romanbsd** [comment]
Chrome is using SSL w/NPN AFAIK. Since Ruby's openssl doesn't support it, there's not much that can be done. If you'd like to hack this thing, you can start from: https://gist.github.com/944386

**Comment by romanbsd** [comment]
Another pointer:
https://github.com/eventmachine/eventmachine/pull/196
